version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "plugin/api"
    schedule:
      interval: "daily"
    ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  - package-ecosystem: "gradle"
    directory: "plugin/core"
    schedule:
      interval: "daily"
    ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  - package-ecosystem: "gradle"
    directory: "plugin/persistence/models"
    schedule:
      interval: "daily"
    ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "org.glassfish.jaxb:jaxb-runtime"
      versions: "> 2.3.2"
    - dependency-name: "jakarta.xml.bind:jakarta.xml.bind-api"
      versions: "> 2.3.2"
  - package-ecosystem: "gradle"
    directory: "plugin/persistence/mysql"
    schedule:
      interval: "daily"
    ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "images/paperInitContainer"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "images/simpleInitContainer"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "images/velocityInitContainer"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "images/waterfallInitContainer"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "images/simpleInitContainer"
    schedule:
      interval: "daily"