apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: paper-hpa-template
  namespace: servers
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: paper-template
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metric:
        name: mc_players_online_total
      target:
        type: AverageValue
        averageValue: 30
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15