apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gamemode-reader
rules:
- apiGroups: ["chrotoscloud.chrotos.net"]
  resources: ["gamemodes"]
  verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minecraft-ingress
  namespace: servers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: minecraft-ingress
  namespace: servers
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gamemode-reader
  namespace: servers
subjects:
- kind: ServiceAccount
  name: default
  namespace: servers
roleRef:
  kind: ClusterRole
  name: gamemode-reader
  apiGroup: rbac.authorization.k8s.io