kind: Service
apiVersion: v1
metadata:
  name: velocity-proxy
  namespace: servers
spec:
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: 25577
  selector:
    app: velocity-proxy
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: velocity-proxy
  namespace: servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velocity-proxy
  template:
    metadata:
      labels:
        app: velocity-proxy
    spec:
      serviceAccountName: minecraft-ingress
      volumes:
        - name: workdir
          emptyDir: {}
        - name: velocity-config
          configMap:
            name: velocity-config
        - name: k8s-token
          projected:
            sources:
            - serviceAccountToken:
                path: k8s-token
                expirationSeconds: 7200
      initContainers:
        - name: velocity-download
          image: ghcr.io/katzen48/chrotoscloud-v2:velocity-init-container
          volumeMounts:
            - name: workdir
              mountPath: /workdir
            - name: velocity-config
              mountPath: /etc/config
          env:
            - name: CLOUD_VERSION
              value: 3.0-SNAPSHOT
            - name: GITHUB_USER
              valueFrom:
                secretKeyRef:
                  name: github-credentials
                  key: GITHUB_USER
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-credentials
                  key: GITHUB_TOKEN
            - name: DB_STRING
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_STRING
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_PASSWORD
            - name: VELOCITY_SECRET
              valueFrom:
                secretKeyRef:
                  name: velocity-secret
                  key: VELOCITY_SECRET
          imagePullPolicy: IfNotPresent
      containers:
        - name: velocity-proxy
          image: openjdk:16-jdk-alpine
          command:
            - java
          args:
            - '-Xms4G'
            - '-Xmx4G'
            - '-jar'
            - server.jar
          workingDir: /opt/proxy
          env:
            - name: DB_STRING
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_STRING
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_PASSWORD
            - name: QUEUE_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: QUEUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
            - name: QUEUE_HOST
              value: rabbitmq.core
            - name: QUEUE_PORT
              value: "5672"
          ports:
            - name: minecraft
              hostPort: 25565
              containerPort: 25577
              protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 4G
            requests:
              cpu: 1
              memory: 3000M
          volumeMounts:
            - name: workdir
              mountPath: /opt/proxy
          livenessProbe:
            tcpSocket:
              port: 25577
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 25577
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 10
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  serviceName: velocity-proxy
