name: Java CI
on: 
  push:
    branches:
    - master
    paths:
    - plugin/**

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: artifactoryPublish
          gradle-version: 7.2
          build-root-directory: plugin
        env:
          CHROTOSCLOUD_TEST_DB_STRING: ${{ secrets.CHROTOSCLOUD_TEST_DB_STRING }}
          CHROTOSCLOUD_TEST_DB_USER: ${{ secrets.CHROTOSCLOUD_TEST_DB_USER }}
          CHROTOSCLOUD_TEST_DB_PASSWORD: ${{ secrets.CHROTOSCLOUD_TEST_DB_PASSWORD }}

      - uses: actions/upload-artifact@v2
        with:
          name: api
          path: plugin/api/build/libs
      - uses: actions/upload-artifact@v2
        with:
          name: core
          path: plugin/core/build/libs
      - uses: actions/upload-artifact@v2
        with:
          name: persistence-models
          path: plugin/persistence/models/build/libs
      - uses: actions/upload-artifact@v2
        with:
          name: persistence-mysql
          path: plugin/persistence/mysql/build/libs